# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setadmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(402, 489)
        # Dialog.setStyleSheet("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 100, 81, 21))
        self.label.setStyleSheet("font: 14pt \"Tempus Sans ITC\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 120, 101, 31))
        self.label_2.setStyleSheet("font: 14pt \"Tempus Sans ITC\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 160, 81, 21))
        self.label_3.setStyleSheet("font: 14pt \"Tempus Sans ITC\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(60, 190, 111, 21))
        self.label_4.setStyleSheet("font: 14pt \"Tempus Sans ITC\";")
        self.label_4.setObjectName("label_4")
        self.partner_name = QtWidgets.QLineEdit(Dialog)
        self.partner_name.setGeometry(QtCore.QRect(240, 100, 113, 20))
        self.partner_name.setObjectName("partner_name")
        self.partner_surname = QtWidgets.QLineEdit(Dialog)
        self.partner_surname.setGeometry(QtCore.QRect(240, 130, 113, 20))
        self.partner_surname.setObjectName("partner_surname")
        self.partner_code = QtWidgets.QLineEdit(Dialog)
        self.partner_code.setGeometry(QtCore.QRect(240, 160, 113, 20))
        self.partner_code.setText("")
        self.partner_code.setObjectName("partner_code")
        self.partner_doc = QtWidgets.QLineEdit(Dialog)
        self.partner_doc.setGeometry(QtCore.QRect(240, 190, 113, 20))
        self.partner_doc.setObjectName("partner_doc")
        self.aceptar = QtWidgets.QPushButton(Dialog)
        self.aceptar.setGeometry(QtCore.QRect(230, 440, 75, 23))
        self.aceptar.setObjectName("aceptar")
        self.anular = QtWidgets.QPushButton(Dialog)
        self.anular.setGeometry(QtCore.QRect(310, 440, 75, 23))
        self.anular.setObjectName("anular")
        self.image_label = QtWidgets.QLabel(Dialog)
        self.image_label.setGeometry(QtCore.QRect(0, 0, 401, 91))
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.partner_info = QtWidgets.QLabel(Dialog)
        self.partner_info.setGeometry(QtCore.QRect(0, 230, 401, 181))
        self.partner_info.setText("")
        self.partner_info.setObjectName("partner_info")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Asignar ADMINISTRADOR"))
        self.label.setText(_translate("Dialog", "Nombre"))
        self.label_2.setText(_translate("Dialog", "Apellido:"))
        self.label_3.setText(_translate("Dialog", "Codigo"))
        self.label_4.setText(_translate("Dialog", "Numero Doc:"))
        self.aceptar.setText(_translate("Dialog", "Aceptar"))
        self.anular.setText(_translate("Dialog", "Anular"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
